insert into category (description) values ('American');
insert into category (description) values ('Italian');
insert into category (description) values ('Maxican');
insert into category (description) values ('Fast Food');
insert into unit_of_measure (uom) values ('TeasSpoon');
insert into unit_of_measure (uom) values ('TableSpoon');
insert into unit_of_measure (uom) values ('Cup');
insert into unit_of_measure (uom) values ('Pinch');
insert into unit_of_measure (uom) values ('Ounce');
insert into unit_of_measure (uom) values ('Each');
insert into unit_of_measure (uom) values ('Dash');
insert into unit_of_measure (uom) values ('Pint');